services:
  postgres:
    image: postgres:latest
    container_name: doctor-office-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  doctor-office:
    container_name: doctor-office-api
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: >
      sh -c "
      npm run migration:generate -- src/database/migrations/complete-tables &&
      npm run migration:run &&
      npm run start:prod
      "
volumes:
  postgres-data:
