services:
  postgres:
    image: postgres:latest
    container_name: Doctor-Office
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: Doctor-Office
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: