POST   http://localhost:3000/doctor
Content-Type: application/json

{
    "firstName": "walid1",
    "lastName": "mg",
    "email": "walid1@gmail.com",
    "specialization": "mzesd",
    "password": "test"
}

###

GET  http://localhost:3000/doctor
Content-Type: application/json

###

POST   http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "walid1@gmail.com",
    "password": "test"
}